const ROUTE_MENU_TOGGLE_ACTION = Redux.createAction("ROUTE_MENU_TOGGLE");
// const ROUTE_SELECT_ACTION = Redux.createAction("ROUTE_SELECT");
const ROUTE_START_ACTION = Redux.createAction("ROUTE_START");
const ROUTE_START_DRIVING_ACTION = Redux.createAction("ROUTE_START_DRIVING");
const ROUTE_CANCEL_ACTION = Redux.createAction("ROUTE_CANCEL");
const ROUTE_CLOSE_ACTION = Redux.createAction("ROUTE_CLOSE");
const ROUTE_STOP_ACTION = Redux.createAction("ROUTE_STOP");
const ROUTE_GO_BACK_ACTION = Redux.createAction("ROUTE_GO_BACK");
const ROUTE_GET_STARTED_ACTION = Redux.createAction("ROUTE_GET");
const ROUTE_GET_SUCCEEDED_ACTION = Redux.createAction("ROUTE_GET_SUCCEEDED");
const ROUTE_GET_FAILED_ACTION = Redux.createAction("ROUTE_GET_FAILED");
const ROUTE_GET_CHUNK_SUCCEEDED_ACTION = Redux.createAction("ROUTE_GET_REST_SUCCEEDED")
const ROUTE_GET_FINISHED_ACTION = Redux.createAction("ROUTE_GET_FINISHED");

const ROUTE_SHOW_HISTORY_ACTION = Redux.createAction("ROUTE_SHOW_HISTORY");
const ROUTE_GET_HISTORY_SUCCEEDED_ACTION = Redux.createAction("ROUTE_GET_HISTORY_SUCCEEDED");
const ROUTE_GET_HISTORY_FAILED_ACTION = Redux.createAction("ROUTE_GET_HISTORY_FAILED");
const ROUTE_CLOSE_HISTORY_ACTION = Redux.createAction("ROUTE_CLOSE_HISTORY");

const ROUTE_RECORD_CLICKED_ACTION = Redux.createAction("ROUTE_RECORD_CLICKED");
const ROUTE_RECORD_YES_ACTION = Redux.createAction("ROUTE_RECORD_YES");
const ROUTE_RECORD_NO_ACTION = Redux.createAction("ROUTE_RECORD_NO");
const ROUTE_POINT_VISITED_ACTION = Redux.createAction("ROUTE_RECORD_POINT_VISITED");
const ROUTE_RECORD_STOP_ACTION = Redux.createAction("ROUTE_RECORD_STOP");
const ROUTE_REORDER_SUCCEEDED_ACTION = Redux.createAction("ROUTE_REORDER_SUCCEEDED");
const ROUTE_REORDER_FAILED_ACTION = Redux.createAction("ROUTE_REORDER_FAILED");
