const SETTINGS_PANEL_TOGGLE_ACTION = Redux.createAction("SETTINGS_PANEL_TOGGLE");
const SETTINGS_ROAD_NAMES_TOGGLE_ACTION = Redux.createAction("SETTINGS_ROAD_NAMES_TOGGLE");
const SETTINGS_MESSAGES_TOGGLE_ACTION = Redux.createAction("SETTINGS_MESSAGES_TOGGLE");
const SETTINGS_OTHER_TRUCKS_TOGGLE_ACTION = Redux.createAction("SETTINGS_OTHER_TRUCKS_TOGGLE");
